language: bash

before_install:
  - sudo apt-get update && sudo apt-get install -y shellcheck jq curl

script:
  - ls -l
#  - cd chap0x04 && bash test.sh; cd ..
  - cd pull-comments && shellcheck *.sh && bash get_threads.sh && bash report.sh; cd ..
  - ls -l
  - pwd

notifications:
  email:
    on_success: never

